#!/usr/bin/env python3
"""Generate a compact 8-bit-alpha bitmap font as a C header.

The desktop clients (panel, exit dialog) must render text without pulling a
font stack (fontconfig/freetype/pango) into the runtime dependency set. This
build-time tool rasterizes ASCII 0x20..0x7E from a system TrueType font into
per-glyph 8-bit alpha bitmaps; the generated data is compiled into the
client library. The font file itself is never embedded or redistributed.

Usage: genfont.py [-o OUTPUT] [--font PATH] [--size PX]

Output: a C header defining xw_glyph[] and xw_font_meta.
"""

import argparse
import os
import sys

DEFAULT_FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/chinese/NotoSansSC-Regular.ttf",
    "/usr/share/fonts/truetype/english/Tinos-Regular.ttf",
]

START, END = 0x20, 0x7E  # printable ASCII


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--font")
    ap.add_argument("--size", type=int, default=16)
    args = ap.parse_args()

    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        print("error: Pillow is required at build time (python3 -m pip install pillow)",
              file=sys.stderr)
        return 1

    font_path = args.font
    if not font_path:
        for c in DEFAULT_FONT_CANDIDATES:
            if os.path.exists(c):
                font_path = c
                break
    if not font_path or not os.path.exists(font_path):
        print("error: no usable system TTF font found", file=sys.stderr)
        return 1

    font = ImageFont.truetype(font_path, args.size)
    glyphs = {}
    ascent, descent = font.getmetrics()
    max_w = 0
    for cp in range(START, END + 1):
        ch = chr(cp)
        try:
            bbox = font.getbbox(ch)
        except Exception:
            continue
        if bbox is None:
            continue
        w = max(1, bbox[2] - bbox[0])
        h = max(1, bbox[3] - bbox[1])
        img = Image.new("L", (w + 2, h + 2), 0)
        d = ImageDraw.Draw(img)
        d.text((-bbox[0] + 1, -bbox[1] + 1), ch, font=font, fill=255)
        glyphs[cp] = (w + 2, h + 2, img)
        max_w = max(max_w, w + 2)

    line_h = ascent + descent
    out = ["/* Generated by tools/genfont.py — DO NOT EDIT.",
           " * Rasterized at build time from: " + os.path.basename(font_path),
           " * (see THIRD-PARTY-LICENSES.md). Only bitmap data is used;",
           " * the font file itself is not embedded or redistributed.",
           " */",
           "#ifndef XW_FONT_DATA_H",
           "#define XW_FONT_DATA_H",
           "",
           "#define XW_FONT_FIRST 0x20",
           "#define XW_FONT_LAST 0x7e",
           "#define XW_FONT_LINE_H %d" % line_h,
           "#define XW_FONT_ASCENT %d" % ascent,
           "",
           "struct xw_glyph {",
           "    uint8_t w, h;",
           "    int8_t xoff, yoff; /* draw offset from pen origin */",
           "    uint8_t adv;       /* advance to next character */",
           "    const uint8_t *bits; /* w*h alpha bytes */",
           "};",
           "",
           "static const uint8_t xw_bits_%d[] = {" % START]

    glyph_table = []
    for cp in range(START, END + 1):
        if cp not in glyphs:
            glyph_table.append("    {0, 0, 0, 0, 0, NULL}, /* 0x%02x */" % cp)
            continue
        w, h, img = glyphs[cp]
        data = list(img.getdata())
        out.append("    /* 0x%02x %r */ " % (cp, chr(cp)) + ", ".join(str(b) for b in data) + ",")
        bbox = font.getbbox(chr(cp))
        # Draw origin: pen at (0, ascent); image holds glyph starting at (xoff, ascent + yoff)
        xoff = bbox[0] - 1
        yoff = bbox[1] - 1 - ascent
        adv = font.getlength(chr(cp))
        glyph_table.append("    {%d, %d, %d, %d, %d, xw_bits_%d}," % (w, h, xoff, yoff, int(adv + 0.5), cp))

    out.append("};")
    out.append("")
    out.append("static const struct xw_glyph xw_glyph_table[] = {")
    out.extend(glyph_table)
    out.append("};")
    out.append("")
    out.append("#endif")

    with open(args.output, "w") as f:
        f.write("\n".join(out) + "\n")
    print("genfont: %d glyphs, line height %d -> %s" % (len(glyphs), line_h, args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
