/* xwc.h — libxwcl: minimal native client helper library for xw.
 *
 * Provides: connection + global binding, shm-backed xdg toplevel
 * windows, layer-shell surfaces, keyboard (client-side xkb) and pointer
 * event forwarding, and ARGB pixel drawing with the build-time bitmap
 * font. No toolkit, no GLib, no fontconfig.
 */
#ifndef XWC_H
#define XWC_H

#include <stdbool.h>
#include <stdint.h>
#include <xkbcommon/xkbcommon.h>

/* the build-time bitmap font tables (generated by tools/genfont.py):
 * metrics macros and glyph tables, two sizes */
#include "xw-font-data.h"

struct xwc;
struct xwc_win;
struct xwc_layer;
struct xwc_tasklist;
struct xwc_task;
struct xwc_wspaces;

/* ---------------------------------------------------------- callbacks */
struct xwc_callbacks {
    void (*key)(struct xwc_win *win, uint32_t keycode, bool down,
                xkb_keysym_t keysym, uint32_t mods, void *ud);
    void (*button)(struct xwc_win *win, uint32_t button, bool down, int x,
                   int y, void *ud);
    void (*motion)(struct xwc_win *win, int x, int y, void *ud);
    void (*axis)(struct xwc_win *win, uint32_t axis, double value, void *ud);
    void (*configure)(struct xwc_win *win, int w, int h, void *ud);
    void (*close)(struct xwc_win *win, void *ud);
    void *ud;
};

/* -------------------------------------------------------- connection */
struct xwc {
    void *display;    /* struct wl_display * */
    void *registry;
    void *compositor;
    void *shm;
    void *seat;
    void *wm_base;
    void *layer_shell;
    void *ddm;
    int n_outputs;
    int output_w, output_h; /* first output logical size */

    /* client-side xkb (keyboard focus state) */
    struct xkb_context *xkb_ctx;
    struct xkb_keymap *xkb_keymap;
    struct xkb_state *xkb_state;
    void *keymap_mmap; /* mapping of the server keymap */
    size_t keymap_size;

    /* pump hook: lets an embedded (in-process) server run while the
     * client waits for a sync; NULL = plain blocking dispatch */
    void (*pump)(void *ud);
    void *pump_ud;

    void *keyboard;         /* wl_keyboard */
    void *pointer;          /* wl_pointer */
    void *output;           /* first wl_output */
    void *output_state;     /* pending output state (xwc-input.c) */

    void *ftm;    /* zwlr_foreign_toplevel_manager_v1 (lazily bound) */
    void *wsm;    /* ext_workspace_manager_v1 (lazily bound) */
    uint32_t ftm_global; /* registry global name (0 = not advertised) */
    uint32_t wsm_global;
    uint32_t wsi_global; /* xw_workspace_info_v1 (lazily bound by the
                            tasklist; annotates tasks with workspaces) */

    void *lock_mgr;       /* ext_session_lock_manager_v1 (bound eagerly;
                             xwc_lock_create needs it and a lock client
                             has no other reason to connect) */
    void *idle_notifier;  /* ext_idle_notifier_v1 (eager; xwc_idle_create) */

    void *focused_owner;  /* win or layer with keyboard focus */
    struct xwc_callbacks focused_cb; /* callback block of the focused owner */
    bool has_focus;
    int ptr_x, ptr_y;     /* last pointer position (surface-local) */
    bool running;

    /* serial of the last input event (enter/button/key) — popup grabs
     * should carry the serial of the click that opened them */
    uint32_t last_serial;

    /* wl_keyboard.repeat_info as advertised by the server (client-side
     * repeat parameters; 0/0 = not received yet) */
    int repeat_rate_hz, repeat_delay_ms;
    bool repeat_info_received;
};

/* Connect to the compositor (NULL socket = $WAYLAND_DISPLAY). Blocks
 * until globals arrive. Returns 0 on success. */
int xwc_connect(struct xwc *c, const char *socket_name);
/* Same, but yields to an in-process compositor via pump while waiting
 * (used by the test harness). */
int xwc_connect_pumped(struct xwc *c, const char *socket_name,
                        void (*pump)(void *ud), void *pump_ud);
/* sync request + wait, yielding through the pump if set */
int xwc_sync(struct xwc *c);
/* Non-blocking drain of our side of the connection (used with an
 * embedded in-process server; also usable standalone). */
int xwc_drain(struct xwc *c);
void xwc_disconnect(struct xwc *c);
/* Dispatch pending events (timeout_ms < 0 = default). Returns 0, or -1
 * on connection error. */
int xwc_dispatch(struct xwc *c, int timeout_ms);
/* Flush the request buffer. */
void xwc_flush(struct xwc *c);

/* ------------------------------------------------------------ window */
struct xwc_win *xwc_win_create(struct xwc *c, const struct xwc_callbacks *cb,
                              const char *title, const char *app_id, int w,
                              int h);
void xwc_win_destroy(struct xwc_win *w);
/* pixels of the current back buffer (ARGB, stride = width) */
uint32_t *xwc_win_pixels(struct xwc_win *w, int *stride);
/* current buffer size */
void xwc_win_size(struct xwc_win *w, int *w_out, int *h_out);
/* attach + damage-everything + commit */
void xwc_win_commit(struct xwc_win *w);
void xwc_win_set_title(struct xwc_win *w, const char *title);
void xwc_win_close(struct xwc_win *w);
/* request a (un)maximize / (un)fullscreen from the client side */
void xwc_win_maximize(struct xwc_win *w, bool on);
void xwc_win_fullscreen(struct xwc_win *w, bool on);
void xwc_win_minimize(struct xwc_win *w);
/* xdg toplevel resource (for foreign-toplevel / activation requests) */
void *xwc_win_toplevel(struct xwc_win *w);
/* wl_surface resource (xdg-activation target, raw protocol tests) */
void *xwc_win_surface(struct xwc_win *w);
/* xdg_surface resource (popup parents, raw protocol tests) */
void *xwc_win_xdg_surface(struct xwc_win *w);
/* mapped state (configure + first commit done) */
bool xwc_win_mapped(struct xwc_win *w);
/* server asked the window to close (xdg_toplevel close event) */
bool xwc_win_closed(struct xwc_win *w);

/* ------------------------------------------------------ layer surface */
struct xwc_layer *xwc_layer_create(struct xwc *c, const struct xwc_callbacks *cb,
                                  uint32_t layer, uint32_t anchors,
                                  int exclusive_zone, int w, int h);
/* 0 = none, 1 = exclusive, 2 = on-demand (must precede mapping) */
void xwc_layer_set_keyboard(struct xwc_layer *l, uint32_t mode);
/* move the surface to another layer (0=background .. 3=overlay) */
void xwc_layer_set_layer(struct xwc_layer *l, uint32_t layer);
void xwc_layer_destroy(struct xwc_layer *l);
uint32_t *xwc_layer_pixels(struct xwc_layer *l, int *stride);
void xwc_layer_commit(struct xwc_layer *l);
void xwc_layer_resize(struct xwc_layer *l, int w, int h);

/* ------------------------------------------------------------- popup */
/* xdg_popup anchored to a layer surface (panel menus, the
 * applications-menu case). Anchor rect is in PARENT-SURFACE
 * coordinates; the popup is placed below-left of the rect with
 * slide/flip constraint adjustment. Lifecycle: create (returns after
 * the first configure) -> configure callback draws + commits ->
 * xwc_popup_grab() (keyboard + dismiss-on-outside-press) -> user
 * interaction -> close callback (popup_done: dismissed by an outside
 * click) or explicit xwc_popup_destroy(). One double-buffered shm
 * pool; menus do not resize while open. */
struct xwc_popup *xwc_popup_create(struct xwc *c, struct xwc_layer *parent,
                                   int anchor_x, int anchor_y,
                                   int anchor_w, int anchor_h, int w, int h,
                                   const struct xwc_callbacks *cb);
void xwc_popup_destroy(struct xwc_popup *p);
uint32_t *xwc_popup_pixels(struct xwc_popup *p, int *stride);
void xwc_popup_commit(struct xwc_popup *p);
/* request the seat grab after the first commit (keyboard focus +
 * outside-press dismissal server-side); uses the last input serial */
void xwc_popup_grab(struct xwc_popup *p);
/* popup_done was received (the compositor dismissed the menu) */
bool xwc_popup_done(struct xwc_popup *p);


/* -------------------------------------- tasklist (foreign-toplevel) */
/* Tracks every toplevel window via wlr-foreign-toplevel-management:
 * title/app_id/state updates arrive as events, `changed` fires after
 * each batch (the panel re-lays-out and redraws).  activate/close map
 * to the compositor's focus / close requests.  The tasklist takes
 * ownership of the manager proxy (xwc_disconnect tolerates that). */
struct xwc_tasklist *xwc_tasklist_create(struct xwc *c,
                                         void (*changed)(void *ud), void *ud);
void xwc_tasklist_destroy(struct xwc_tasklist *tl);
/* list iteration, in mapping order */
struct xwc_task *xwc_tasklist_first(struct xwc_tasklist *tl);
struct xwc_task *xwc_task_next(struct xwc_task *task);
/* attributes (buffers are owned by the tasklist) */
const char *xwc_task_title(struct xwc_task *task);
const char *xwc_task_app_id(struct xwc_task *task);
bool xwc_task_active(struct xwc_task *task);
bool xwc_task_minimized(struct xwc_task *task);
/* 0-based workspace of the window, from xw-workspace-info-v1 when the
 * compositor offers it. -1 = sticky (on every workspace);
 * -2 = unknown (compositor without the protocol, or before the first
 * event). The pager treats -2 as "show on the current workspace". */
int xwc_task_workspace(struct xwc_task *task);
/* requests: focus (+ un-minimize) / close the window */
void xwc_tasklist_activate(struct xwc_tasklist *tl, struct xwc_task *task);
void xwc_tasklist_close(struct xwc_tasklist *tl, struct xwc_task *task);

/* ----------------------------------------- workspaces (ext-workspace) */
/* Mirrors the compositor workspace list (names + active state);
 * activate(i) requests a workspace switch.  `changed` fires after each
 * manager `done` batch. */
struct xwc_wspaces *xwc_wspaces_create(struct xwc *c,
                                       void (*changed)(void *ud), void *ud);
void xwc_wspaces_destroy(struct xwc_wspaces *wl);
int xwc_wspaces_count(struct xwc_wspaces *wl);
const char *xwc_wspaces_name(struct xwc_wspaces *wl, int idx);
bool xwc_wspaces_active(struct xwc_wspaces *wl, int idx);
void xwc_wspaces_activate(struct xwc_wspaces *wl, int idx);

/* ------------------------------------------------------------- drawing */
/* All drawing operates on ARGB8888 buffers; colors are 0xAARRGGBB with
 * straight alpha composited over the destination. stride is in pixels. */
void xwc_fill_rect(uint32_t *pix, int stride, int w, int h, int x, int y,
                   int rw, int rh, uint32_t color);
void xwc_draw_hline(uint32_t *pix, int stride, int w, int h, int x, int y,
                    int len, uint32_t color);
void xwc_draw_vline(uint32_t *pix, int stride, int w, int h, int x, int y,
                    int len, uint32_t color);
/* Draws text (ASCII 0x20-0x7e). Returns the new x position. */
int xwc_draw_text(uint32_t *pix, int stride, int w, int h, int x, int y,
                  const char *text, uint32_t color);
int xwc_text_width(const char *text);
/* The same, in the second (larger, 24 px) raster: for tall bars, menu
 * rows and calendar headers where the base raster looks undersized. */
int xwc_draw_text2(uint32_t *pix, int stride, int w, int h, int x, int y,
                   const char *text, uint32_t color);
int xwc_text_width2(const char *text);
#define XWC_LINE_H XW_FONT_LINE_H
#define XWC_ASCENT XW_FONT_ASCENT
#define XWC_LINE2_H XW_FONT2_LINE_H
#define XWC_ASCENT2 XW_FONT2_ASCENT

/* roundrect outline+fill, a UI primitive used by all clients */
void xwc_draw_box(uint32_t *pix, int stride, int w, int h, int x, int y,
                  int bw, int bh, uint32_t fill, uint32_t border);

/* ---------------------------------------------------------------- icons */
/* XDG icon pipeline: theme lookup + PNG/XPM decode + rescale + cache.
 *
 * xwc_icon_get(name, size) resolves an icon the way the icon theme spec
 * (freedesktop) prescribes, simplified: no index.theme inheritance
 * chains; the search walks $XDG_DATA_HOME/icons, $HOME/.icons, then
 * $XDG_DATA_DIRS/icons (and /usr/share/pixmaps flat) under the theme
 * named by $XW_ICON_THEME, then "hicolor", for "<name>.png|xpm" at any
 * size; the file whose size is closest >= the request wins (largest
 * otherwise, downscaled with box filtering). SVG-only results cannot be
 * rendered (no vector stack) and are skipped — a documented deviation.
 * Names containing '/' load that file directly. PNG needs the optional
 * libpng (XW_PNG=auto); XPM is always parsed in-house.
 *
 * The returned surface is owned by the cache (valid until
 * xwc_icon_flush()); NULL = not found. Single-threaded clients only. */
struct xwc_icon {
    int w, h;         /* scaled surface size */
    uint32_t *pix;    /* ARGB, w*h, row-major */
};
const struct xwc_icon *xwc_icon_get(const char *name, int size);
/* drop every cached surface + the on-disk index (tests, config reload) */
void xwc_icon_flush(void);
/* PNG decoding compiled in? (XW_PNG) */
bool xwc_icon_png(void);
/* blit an icon (alphas over the destination) scaled to `size` box,
 * centered in a size x size cell at (x, y) */
void xwc_draw_icon(uint32_t *pix, int stride, int w, int h, int x, int y,
                   const struct xwc_icon *ic, int size);

/* ---------------------------------------------------- session lock */
/* ext-session-lock-v1 client. xwc_lock_create locks the session and
 * creates one lock surface for the bound (first) output; v0 of the
 * library tracks a single output, so exactly one lock surface is
 * created — the server side itself supports any number of outputs.
 *
 * Lifecycle: create -> configure(w,h) callback fires with the output
 * size (draw into xwc_lock_pixels() and call xwc_lock_commit() there)
 * -> locked() event once the compositor presented the locked frame
 * (or finished() if the lock was denied: another client holds it).
 * Keyboard/pointer events of the lock surface arrive through the
 * key/button/motion callbacks while the session is locked. Unlock via
 * xwc_lock_unlock() (roundtrips so the server processes it). */
struct xwc_lock;
struct xwc_lock_cbs {
    void (*locked)(struct xwc_lock *l, void *ud);
    void (*finished)(struct xwc_lock *l, void *ud);
    /* draw + commit the lock surface for the new size */
    void (*configure)(struct xwc_lock *l, int w, int h, void *ud);
    void (*key)(struct xwc_lock *l, uint32_t keycode, bool down,
                xkb_keysym_t keysym, uint32_t mods, void *ud);
    void (*button)(struct xwc_lock *l, uint32_t button, bool down, int x,
                   int y, void *ud);
    void (*motion)(struct xwc_lock *l, int x, int y, void *ud);
    void *ud;
};
struct xwc_lock *xwc_lock_create(struct xwc *c, const struct xwc_lock_cbs *cb);
void xwc_lock_destroy(struct xwc_lock *l);
/* pixels of the current back buffer (ARGB, stride = width) */
uint32_t *xwc_lock_pixels(struct xwc_lock *l, int *stride);
void xwc_lock_size(struct xwc_lock *l, int *w, int *h);
/* attach + damage-everything + commit */
void xwc_lock_commit(struct xwc_lock *l);
bool xwc_lock_locked(struct xwc_lock *l);
bool xwc_lock_finished(struct xwc_lock *l);
/* unlock_and_destroy + wl_display roundtrip (the protocol requires the
 * sync: without it the server may not have processed the unlock). */
void xwc_lock_unlock(struct xwc_lock *l);

/* ------------------------------------------------------- idle notify */
/* ext-idle-notify-v1 client: one notification with a timeout. */
struct xwc_idle;
struct xwc_idle *xwc_idle_create(struct xwc *c, uint32_t timeout_ms,
                                 void (*idled)(void *ud),
                                 void (*resumed)(void *ud), void *ud);
void xwc_idle_destroy(struct xwc_idle *i);

#endif /* XWC_H */
